# Site settings
title: "Laszlo Fogas"
tag_text: "Laszlo Fogas"
description: Laszlo Fogas, a self employed DevOps consultant going into products

destination: public
source: src
exclude: ['node_modules']

# Build settings
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-sitemap
