# Site settings
title: Laszlo Fogas
tag_text: laszlo.cloud
description: I’m Laszlo Fogas, freelance software consultant. Engineering leadership and Devops expert; former early employee & Director of Engineering @ FalconIO.

# Build settings
markdown: kramdown
sass:
  style: compressed
