# Site settings
title: "Laszlo Fogas"
tag_text: "Laszlo Fogas"
description: I'm Laszlo Fogas, Devops Consultant. I help software teams to move their Docker experiments to production. Check out my roadmap for Kubernetes projects!

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
  - jekyll-sitemap
