# Site settings
title: "Laszlo Fogas"
tag_text: "Laszlo Fogas"
description: Hi I'm Laszlo Fogas, Devops consultant. My mission is elevating team cultures through automation and tooling. As a former engineering director I gained the perspective to effectively operate on many levels of your organization. I feel home in developer advocacy, building CI/CD pipelines and Cloud infrastructure, up to stakeholder management.

# Build settings
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-sitemap
