# Site settings
title: "laszlo.cloud"
tag_text: "laszlo.cloud"
description: I'm Laszlo Fogas, Devops Consultant. I help software teams to move their Docker experiments to production. See my roadmap for Kubernetes projects.

# Build settings
markdown: kramdown
sass:
  style: compressed
