# Site settings
title: "Move your Docker experiments to production"
tag_text: "laszlo.cloud"
description: I'm Laszlo Fogas, Devops Consultant. I help software teams to move their Docker experiments to production. Check out my roadmap for Kubernetes projects!

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
  - jekyll-sitemap
